name: ch02_realtime_quiz
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  # --- UI 관련 패키지 ---
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  velocity_x: ^4.3.1
  flutter_hooks: ^0.21.2

  # --- 상태관리(State Management) ---
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # --- Firebase Core/플러그인 ---
  firebase_core: ^3.14.0

  # --- 데이터베이스/스토리지 ---
  cloud_firestore: ^5.6.9
  firebase_storage: ^12.4.7

  # --- 인증(Authentication) ---
  firebase_auth: ^5.6.0

  # --- 데이터 모델/직렬화(Model/Serialization) ---
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  
  # --- 로깅/에러 추적 ---
  # 예: logger, sentry_flutter 등 (아직 없음)


dev_dependencies:
  # --- 테스트(Test) ---
  flutter_test:
    sdk: flutter

  # --- 개발 도구/코드 생성(Dev Tools/Code Generation) ---
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.5
  build_runner: ^2.4.15
  custom_lint: ^0.7.5
  riverpod_lint: ^2.6.5
  freezed: ^3.0.6
  json_serializable: ^6.9.5

  # --- 테스트 도우미/모킹 ---
  # 예: mockito, fake_async 등 (아직 없음)


flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
