// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEY6ufpyNBTONgaMGrBMpm3u5NQZyO6mE',
    appId: '1:643881133335:web:c3e601c17592e3861e0352',
    messagingSenderId: '643881133335',
    projectId: 'fc-ch02-realtime-quiz',
    authDomain: 'fc-ch02-realtime-quiz.firebaseapp.com',
    storageBucket: 'fc-ch02-realtime-quiz.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF4-ka4JMPCjrCs75kFAmWFVKgAEg-oUM',
    appId: '1:643881133335:android:8130850bf97ed1cb1e0352',
    messagingSenderId: '643881133335',
    projectId: 'fc-ch02-realtime-quiz',
    storageBucket: 'fc-ch02-realtime-quiz.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBmQg7tsWgy6_IV6Nv3nZXaziJHWJZLpKU',
    appId: '1:643881133335:ios:604915ec533a20771e0352',
    messagingSenderId: '643881133335',
    projectId: 'fc-ch02-realtime-quiz',
    storageBucket: 'fc-ch02-realtime-quiz.firebasestorage.app',
    iosBundleId: 'com.example.ch02RealtimeQuiz',
  );

}